def gin_words():
    gin_list = ['#Scotland'
        , '#Scottish'
        , '@TheGSD_Co'
        , '#plantingtreesandsavingbees'
        , '#Glasgow'
        , '#GlasweGIN'
        , '#GardenShedGin'
        , '#TheGSDco'
        , '@partickduckclub'
        , '@LebowskisSouth'
        , '@Lebowskis_West'
        , '@LebowskisBarEdi'
        , '@gardenerglasgow'
        , '@The_Gantry'
        , '@TVOBedin'
        , '#gin'
        , '#gintonic'
        , '@GinFestival'
        , '@ginfestuk'
        , '@Ginfestival2018'
        , '#ginoclock'
        , '#ginfestival'
        , '#scottishgins'
        , '#ginlovers'
        , '#gintasting'
        , '#gincocktails']
    return gin_list


def f1_words():
    f1_list = ['#f1'
        , '#motorsports'
        , '@MercedesAMGF1'
        , '@F1'
        , '@redbullracing'
        , '@MotorsportsHub'
        , '@ToroRosso']
    return f1_list

def mudano_banking_words():
    mudano_banking_list = ['#Scotland'
        , '#london'
        , '#mudano'
        , '@everMudano'
        , 'everMudano'
        , 'lloydsbanking'
        , '#datascience'
        , '#ai'
        , '#artificialintelligence'
        , '#ArtificialIntelligence '
        , '#deliveryscience'
        , '#delivervalue'
        , '#projectmanagement'
        , '#ScotlandIsNow'
        , '#InvestScotland'
        , '#ChangeTheWorld'
        , '#prototype'
        , '@scotgov'
        , '#tech'
        , '#banking'
        , '#finance'
        , '#LloydsBanking'
        , '#gdpr'
        , ' #BankFraud'
        , '#MachineLearning'
        , '#DeepLearning'
        ,'#BigData'
        , '#NeuralNetworks'
        , '#datamining'
        , '#behaviouralscience'
        , '#innovativefinance'
        , '#data'
        , '#analytics'
        , 'mudano']
    return mudano_banking_list
